ads = "//*[contains(@id,'img-image')]"
btn_close_ads = "//*[contains(@id,'icon-close-button')]"
search_text_field = "//*[@id='txt-searchBox-input']"
btn_search = "//*[@id='btn-searchBox-input']"
filter_params = "//*[text()='param']//preceding::div[2]"
btn_add_to_cart = "//button[contains(@id, 'btn-addCart')]"
ele = "//div[text()='Delivery']//ancestor::div[3][contains(@id,'productGrid')]"
btn_viewCart = "//*[@id='lnk-viewCart']"
pop_up_add_success = "//*[@type='success']"
btn_cart = "//*[@id='btn-openMiniCart']"
btn_continue_shopping = "//*[@id='lnk-viewHome']/button"